- id: '1645793480899'
  alias: Delay Solar Diverter
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.myenergi_eddi_status
    to: Max temp reached
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.turn_off_solar_diverter_below_100w_pv
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.turn_on_solar_diverter_above_100w_pv
  - device_id: 1c434db3f2899078cbe101a7a54deede
    domain: select
    entity_id: select.myenergi_eddi_operating_mode
    type: select_option
    option: Stopped
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - device_id: 1c434db3f2899078cbe101a7a54deede
    domain: select
    entity_id: select.myenergi_eddi_operating_mode
    type: select_option
    option: Normal
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.turn_off_solar_diverter_below_100w_pv
  - service: automation.turn_on
    data: {}
    target:
      entity_id: automation.turn_on_solar_diverter_above_100w_pv
  mode: single
- id: '1645793972068'
  alias: Turn false Garage Light off
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 9baba3ff60ce677d613ac519c125e6e4
    entity_id: light.garage_light_right
    domain: light
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: device
    device_id: 6b6ac76533c5741284ac3f254fdb79f0
    domain: lock
    entity_id: lock.conexis_garage_door
    type: is_locked
  action:
  - type: turn_off
    device_id: 9baba3ff60ce677d613ac519c125e6e4
    entity_id: light.garage_light_right
    domain: light
  mode: single
- id: '1645795348588'
  alias: Turn on Solar Diverter
  description: ''
  trigger:
  - type: battery_level
    platform: device
    device_id: 576c6ce6230a18a2de653c8e254dfbfb
    entity_id: sensor.solax_battery_capacity
    domain: sensor
    above: 95
  condition:
  - type: is_power
    condition: device
    device_id: 576c6ce6230a18a2de653c8e254dfbfb
    entity_id: sensor.solax_pv_total_power
    domain: sensor
    above: 500
  action:
  - service: select.select_option
    data:
      option: Back Up Mode
    target:
      entity_id: select.solax_charger_use_mode
  - device_id: 1c434db3f2899078cbe101a7a54deede
    domain: select
    entity_id: select.myenergi_eddi_operating_mode
    type: select_option
    option: Normal
  mode: single
- id: '1645795423311'
  alias: Turn off Solar Diverter below 100w PV
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: 576c6ce6230a18a2de653c8e254dfbfb
    entity_id: sensor.solax_pv_total_power
    domain: sensor
    below: 400
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - device_id: 1c434db3f2899078cbe101a7a54deede
    domain: select
    entity_id: select.myenergi_eddi_operating_mode
    type: select_option
    option: Stopped
  - service: select.select_option
    data:
      option: Self Use Mode
    target:
      entity_id: select.solax_charger_use_mode
  mode: single
- id: '1645990036998'
  alias: New Automation
  description: ''
  trigger:
  - type: energy
    platform: device
    device_id: e542bbaca249d970af1a30180277e247
    entity_id: sensor.energy_production_today
    domain: sensor
    below: 8
  condition:
  - type: is_battery_level
    condition: device
    device_id: 576c6ce6230a18a2de653c8e254dfbfb
    entity_id: sensor.solax_battery_capacity
    domain: sensor
    below: 50
  - condition: time
    after: 02:00
    before: 03:30
  action:
  - service: select.select_option
    data:
      option: Force Time Use
    target:
      entity_id: select.solax_charger_use_mode
  mode: single
