homeassistant:
  # Customization file
#  customize: !include customize.yaml
  packages: !include_dir_named packages
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/24

camera:
#  - platform: generic
#    name: Doorbell Live
#    stream_source: !secret cam_doorbell
  - platform: generic
    name: Drive Live
    stream_source: !secret cam_drive
  - platform: generic
    name: Front Garden Live
    stream_source: !secret cam_front_garden
  - platform: generic
    name: Rear Garden Live
    stream_source: !secret cam_rear_garden

light:
  - platform: group
    name: Bathroom Lights
    entities:
      - light.bathroom_rgbw_1_rgb
      - light.bathroom_rgbw_2_rgb
      - light.bathroom_rgbw_3_rgb

logger:
  default: warning

octopusagile:
  region_code: "E"
  mpan: !secret octo_mpan
  serial: !secret octo_serial
  auth: !secret octo_api_key
  startdate: "2020-04-25"
  gorate: 4.5
  # You can leave godayrate out to go by 
  # Agile rates outside of offpeak period
  godayrate: 13.72
  gotimes:
  - "02:30:00"
  - "03:00:00"
  - "03:30:00"
  - "04:00:00"
  - "04:30:00"
  - "05:00:00"

panel_iframe:
  double_take:
    title: "Double-Take"
    url: !secret double_take_url
    icon: mdi:shield-account
    require_admin: true
  file_browser:
    title: "File-Browser"
    url: !secret file_browser_url
    icon: mdi:file-document-edit
    require_admin: true
  snapeshire:
    title: "Snapeshire"
    url: !secret snapeshire_url
    icon: mdi:home-assistant
    require_admin: true
  volumio:
    title: "Volumio"
    url: !secret volumio_url
    icon: mdi:record-player


python_script:

stream:
  ll_hls: true
  part_duration: 0.75
  segment_duration: 6

# Text to speech
tts:
  - platform: marytts
    host: !secret host
    port: 59125
    codec: 'WAVE_FILE'
    voice: 'dfki-spike-hsmm'
    language: 'en_GB'

withings:
  client_id: !secret withings_id
  client_secret: !secret withings_secret
  use_webhook: true

automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml